language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
  matrix:
    - MASTER=true
    - LAST_RELEASE=true
matrix:
  allow_failures:
    - env: MASTER=true
  fast_finish: true
before_install:
- whoami
- cp travis.cfg buildout.cfg
install:
# Troca a linha do extends do último release para só apontar para as pinagens do Plone 4.3.x,
# e adiciona 'eggs+=' e 'zcml+=' para poder funcionar o buildout (senão dá o erro
# "Error: Referenced option does not exist: buildout zcml")
- test $MASTER && sed -ie 's/.*http:\/\/downloads\.plone\.org\.br\/release\/.*/    http:\/\/dist\.plone\.org\/release\/4\.3-latest\/versions\.cfg\n\neggs\+=\n\nzcml+=/' buildout.d/base.cfg || true
- python bootstrap.py
- bin/buildout annotate
- bin/buildout
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- PLONE_CSRF_DISABLED=true bin/test
notifications:
  irc: irc.freenode.org#plonegovbr
