language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
addons:
  firefox: 45.9.0esr
env:
  global:
  - PLONE_CSRF_DISABLED=true
# DOCKER_LOGIN
  - secure: IiDrW4wO5sPO67bDoLniS/fp6HM6CpRHUi5b5rwbzibXjg59n9wIdQDmv7PuJRxRG8TCTS6HvGtbMXE1NQ0WuBIN6rvOUBzX72tAxQBnUbAggp2yA4U6xQrcDVCBqZtgt7CUGcRNbEQKl96YNjQvsuVfMQ02lHGz4j4TduzhZtg=
# DOCKER_PASS
  - secure: Nz00qh28EYnfhT0WM32lYMt0kWkw2JcWeb3sh4ttVn6CnM5+RiN1I++4ZXC2iHD7GIrpvfSVdIie2JNr99LYNyRlGdiJv+eOO9IStGrXH8CRLyw0wzBTOItRz/pm3AYFAF9GDALrDtF3Xb8Nt+XjcfSwpFuj1fsXn4KHJp77I5E=
  matrix:
  - DEVELOPMENT=true
  - PRODUCTION=true
matrix:
  allow_failures:
  - env: PRODUCTION=true
  fast_finish: true
before_install:
- test $DEVELOPMENT && cp travis-development.cfg buildout.cfg || cp travis-production.cfg
  buildout.cfg
- sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.5/goss-linux-amd64
  -o /usr/local/bin/goss
- sudo chmod +rx /usr/local/bin/goss
install:
- python bootstrap.py --setuptools-version=36.3.0 --buildout-version=2.9.5
- bin/buildout annotate
- bin/buildout
- grep -q 'brasil.gov.portal' bin/instance
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bin/test -s brasil.gov.agenda
- bin/test -s brasil.gov.barra
- bin/test -s brasil.gov.portal
- bin/test -s brasil.gov.portlets
- bin/test -s brasil.gov.temas
- bin/test -s brasil.gov.tiles
- bin/test -s brasil.gov.vcge
- docker run --rm -i lukasmartinelli/hadolint /bin/hadolint --ignore DL3002 --ignore
  DL3004 --ignore SC2086 --ignore DL3008 - < docker/Dockerfile
- docker build -t plonegovbr/plonegovbr:test docker
- docker run -d -p 8080:8080 --name plonegovbr plonegovbr/plonegovbr:test
- sudo goss validate --retry-timeout 180s --sleep 2s
after_failure:
- grep brasil.gov bin/test
notifications:
  irc: irc.freenode.org#plonegovbr
deploy:
  provider: script
  script: script/deploy.sh
  on:
    tags: true
